<?php


namespace App;


class addPhrase
{
    protected static $AddPhrase = [
        'incorrect_password' => 'Le mot de passe incorrect',
        'login_incorrect' => 'Le login n\'existe pas',
        'user_list' => 'User list',
        'user_edit' => 'User edit',
        'no_privilege_admin' => 'Vous n\'avait pas les privilège Admin !',
        'login_is_already_taken' => 'Le login est déjà pris !',
        'the_e_mail_address_is_not_valid' => 'L\'adresse e-mail n\'est pas valide',
        'you_cannot_delete_your_account' => 'Vous ne pouvez pas supprimer votre compte',
        'Don_t_you_have_an_account' => 'Vous n\'avez pas de compte?',
        'creator_article' => 'Créer article',
        'you_do_not_have_permission_to_view_this_page_or_perform_this_action' => 'Vous n\'êtes pas autorisé à afficher cette page ou à effectuer cette action.',
        'category' => 'Category',
        'the_login_must_have_more_than_4_characters' => 'Le login doit avoir plus de 4 caractères',
        'The_passwords_don_t_match' => 'Les password ne corresponde pas !',
        'please_enter_all_fields' => 'Veuillez saisir tous les champs.',
        'incorrect_login_or_password' => 'Login ou mot de passe incorrect',
        'all_product' => 'Tous nos produits',
        'there_are_no_categories_created' => 'Il n\'y a pas de catégories créées',
        'carts' => 'Paniers',
        'continue' => 'Continue',
        'address' => 'Adresse',
        'categories_list' => ' Tous les rayons Composants',
        'carts_addresses' => 'Adresses',
        'select_addresses' => 'Adresse de facturation/livraison',
        'carts_finalize' => 'Récapitulatif',
        'in_progress' => 'En attente de validation',
        'state' => 'Statut',
        'validate' => 'Validée',
        'cancel' => 'Annuelle',
        'no_state' => 'Pas de statut',
        'invoice' => 'Facture',
        'coupon_value' => 'Remise fixe',
        'coupon_percent' => 'Poucentage',
        'coupon' => 'Coupon',
        'coupon_type' => 'Coupon type',
        'coupon_title' => 'Titre coupon',
        'discount_type' => 'Coupon type',
        'price_total_x' => 'Prix total ({value})',
        'order' => 'Commande',
        'orders' => 'Commandes',
        'payment_info' => 'Information de paiement',
        'items' => 'Articles',
        'purchase_request_key' => 'Clé de demande d\'achat',
        'order_state' => 'État de la commande',
        'order_total' => 'Total de la commande',
        'unknown_address' => 'Adresse inconnue',
        'sale_discount' => 'Réductions de vente',
        'sub_total' => 'Total',
        'Coupon_log' => 'Historique coupon',
        'payment_type_product' => 'Product',
        'action' => 'Action',
        'transaction_id' => 'Transaction ID',
        'payment_profile' => 'Profil de paiement',
        'payment_provider_log' => 'Historique du fournisseur de paiement',
        'payment_provider_list' => 'Historique des prestataires de paiement',
        'purchasable_item' => 'Article acheté',
        'purchasable_details' => 'Détail article',
        'coupon_log' => 'Historique des coupons',
        'coupon_log_list' => 'Historique des coupons',
        'log_type_payment' => 'Payment',
        'log_type_information' => 'Information',
        'log_type_error' => 'Error',
        'log_type_cancel' => 'Cancellation',
        'addresses' => 'Adresses',
        'code' => 'Code',
        'valid_from' => 'Valable à partir de',
        'valid_for' => 'Valable pour',
        'upload_img_default' => 'Image par défaut',
        'price' => 'Prix',
        'stock' => 'Sotck',
        'upload_img' => 'Upload image',
        'product' => 'Produit',
        'product_list' => 'Porduit list',
        'name' => 'Titre',
        'display_order' => 'Ordre d\'affichage',
        'coupon_list' => 'Coupon list',
        'addresses_log' => 'Historique des adresses',
        'address_name' => 'Nom adresse',
        'n_0' => 'n°',
        'first_name' => 'Nom',
        'last_name' => 'Prénom',
        'sex_m' => 'Masculin',
        'sex_mme' => 'Féminin',
        'additional_address' => 'Complaiment d \'adresse',
        'zip_code' => 'Code postale',
        'city' => 'Ville',
        'cell_phone' => 'Téléphone portable',
        'landline_phone' => 'Téléphone fixe',
        'log_date' => 'Date',
        'sex' => 'Sexe',
        'cron' => 'Entrées cron',
        'country' => 'Pays',
        'sales_tax_rate' => 'Taxe de vente',
        'countries_list' => 'Taxe de vente',
        'from' => 'À partir de',
        'sales_tax' => 'Taxe de vente'

    ];

    public static function addPhrase()
    {
        return self::$AddPhrase;
    }
}